### PR TITLE
Enable setting test arguments with '-args' 

### PR DESCRIPTION
**Pull request by dvelitchkov**
Test arguments are now correctly passed in. Users have to set their `go.buildFlags`, e.g.:

```go
"go.buildFlags": [
        "-args",
        "-foo",
        "i_am_foo",
        "-bar",
        "i_am_bar"
    ]
```

### CODE REVIEW

**Comment by dvelitchkov** [comment]
This is for #1534

**Comment by ramya-rao-a** [comment]
I tried the test code and flags you provided, but I get the below error
Am I missing something?

screen shot 2018-04-03 at 11 05 57 pm

**Comment by dvelitchkov** [comment]
Sorry for the delay. 
I think this PR should be closed - this was a bad idea. What I'm doing can be accomplished by setting VS code project debug settings, no need to mess with build flags.

**Comment by ramya-rao-a** [comment]
Can you update your solution in #1534 and close it as well?

**Pull request closed without merging**
