### PR TITLE
added go.inferGopath. Similar to GoSublime's use_gs_gopath

### PR DESCRIPTION
**Pull request by codmajik**
I would like to propose this implementation for the feature request raised in #757

### CODE REVIEW

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by ramya-rao-a** [comment]
@codmajik Thanks for the PR!

A few notes:

Take a case where the user has set `go.gopath` to a particular path, and also set `go.inferGopath` to true. Then according to your current logic:

- the inferred path wins. I was wondering if this should be the other way around. 
- If the user then sets `go.inferGopath` to false, you will need to reload the VS Code window for the change to take effect. If we only infer the go path, when there is no `go.gopath`, then you won't need the reload

Also, can you write a unit test for this as well? You will have to change `updateGoPathGoRootFromConfig` to take the `goConfig` as a parameter to do that.

**Comment by codmajik** [comment]
@ramya-rao-a Thanks for your feedback.

The case you provided is the actual use case for this and also the current implementation in GoSublime. 

Where `go.gopath` is set in the global config and `go.inferGopath` is set in workspace config. Though
I am adding code to allow the reserve when `go.inferGopath` is global and  `go.gopath` is set in workspace

**Comment by ramya-rao-a** [comment]
@codmajik I am assuming that when you say "global config", you mean the "User settings" in VS Code.

All configurations defined in the `package.json` are available for changes in both Workspace and User settings.

By the time you fetch the settings by `vscode.workspace.getConfiguration()`,  Workspace and User settings are already merged (workspace overrides user), so as an extension author, we have no idea if the value for a config was set in global/user settings or workspace settings.

Therefore, in our case here both `go.gopath` and `go.infergopath` can be set either in User or Workspace settings. We need to adapt for both.

Thinking more on this, it makes sense for the inferred path to win when both `go.gopath` and `go.inferGopath` are set.

**Comment by codmajik** [comment]
@ramya-rao-a Thanks. 

I made those changes on my local checkout. I know it is not needed but I can create a new pull request with that as improvements. I just need to figure out how to test this with your current test suite.

btw `vscode.workspace.getConfiguration('go').inspect('gopath')` would give you the User Setting and Workspace Setting separately.

**Comment by ramya-rao-a** [comment]
@codmajik Never mind the tests, I was thinking of doing a major refactoring in the unit test area soon, I can take care of that.

What changes are you referring to exactly?

**Comment by codmajik** [comment]
@ramya-rao-a, changes to make sure that if `go.gopath` is set in the workspace config and but `go.inferGopath` is set in User Settings then workspace `go.path` would take precedence.

PS: should I delete the branch?

**Comment by ramya-rao-a** [comment]
@codmajik I think its fine the way it is. You can delete your branch.

I have updated the descriptions for both `go.gopath` and `go.inferGopath` to reflect that the latter overrides the former. 

There is command `Go: Current GOPATH` that shows the GOPATH being used by the extension. It says: "Current GOPATH: ..."
We can update that to say "Current GOPATH is inferred from the workspace root: ..." when the GOPATH is inferred.

You can send a separate PR for that.

**Pull request merged**
