### PR TITLE
Fix stackframe https://github.com/Microsoft/vscode-go/issues/1987

### PR DESCRIPTION
**Pull request by freezlite**
September update for vscode breaks vscode-go debugger. Commit that cause trouble https://github.com/Microsoft/vscode/commit/cef0992fff3900ee8f86fdcdbbed6801b636f9ed#diff-2e2415aa74df8729e8b700ae772baf79R61

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
Thanks for the investigation @freezlite!

Can you provide a small sample code where I can get a repro of the `<autogenerated>` case? I cant repro it with the code that I have.

**Comment by freezlite** [comment]
Delve return "<autogenerated>" for type casting for example, maybe in some different situations. I think no need to check for path if delve return autogenerated

**Comment by ramya-rao-a** [comment]
I would still appreciate a code sample where `<autogenerated>` is returned by delve

**Comment by freezlite** [comment]
https://github.com/goji/goji/blob/master/dispatch.go#L17

**Comment by freezlite** [comment]
Next stack after this
https://github.com/goji/goji/blob/master/dispatch.go#L17
` 2  0x0000000000a3e67c in bitbucket.org/my/project/vendor/goji%2eio.dispatch.ServeHTTP
    at /home/freezlite/go/src/bitbucket.org/my/project/vendor/goji.io/dispatch.go:17
 3  0x0000000000a4200b in bitbucket.org/my/project/vendor/goji%2eio.(*dispatch).ServeHTTP
    at <autogenerated>:1`

**Comment by freezlite** [comment]
Next stack after this
https://github.com/goji/goji/blob/master/dispatch.go#L17
Output from delve itself
` 2  0x0000000000a3e67c in bitbucket.org/my/project/vendor/goji%2eio.dispatch.ServeHTTP
    at /home/freezlite/go/src/bitbucket.org/my/project/vendor/goji.io/dispatch.go:17
 3  0x0000000000a4200b in bitbucket.org/my/project/vendor/goji%2eio.(*dispatch).ServeHTTP
    at <autogenerated>:1`

**Comment by freezlite** [comment]
Next stack after this
https://github.com/goji/goji/blob/master/dispatch.go#L17
Output from delve itself
` 2  0x0000000000a3e67c in bitbucket.org/my/project/vendor/goji%2eio.dispatch.ServeHTTP
    at /home/freezlite/go/src/bitbucket.org/my/project/vendor/goji.io/dispatch.go:17
 3  0x0000000000a4200b in bitbucket.org/my/project/vendor/goji%2eio.(*dispatch).ServeHTTP
    at <autogenerated>:1`

**Comment by freezlite** [comment]
Next stack after this
https://github.com/goji/goji/blob/master/dispatch.go#L17
Output from delve itself
` 2  0x0000000000a3e67c in bitbucket.org/my/project/vendor/goji%2eio.dispatch.ServeHTTP
    at /home/freezlite/go/src/bitbucket.org/my/project/vendor/goji.io/dispatch.go:17
 3  0x0000000000a4200b in bitbucket.org/my/project/vendor/goji%2eio.(*dispatch).ServeHTTP
    at <autogenerated>:1`

**Comment by freezlite** [comment]
Next stack after this
https://github.com/goji/goji/blob/master/dispatch.go#L17
Output from delve itself
` 
2  0x0000000000a3e67c in bitbucket.org/my/project/vendor/goji%2eio.dispatch.ServeHTTP
    at /home/freezlite/go/src/bitbucket.org/my/project/vendor/goji.io/dispatch.go:17
 3  0x0000000000a4200b in bitbucket.org/my/project/vendor/goji%2eio.(*dispatch).ServeHTTP
    at <autogenerated>:1
`

**Comment by freezlite** [comment]
Next stack after this
https://github.com/goji/goji/blob/master/dispatch.go#L17
Output from delve itself
` 
2  0x0000000000a3e67c in bitbucket.org/my/project/vendor/goji%2eio.dispatch.ServeHTTP
    at /home/freezlite/go/src/bitbucket.org/my/project/vendor/goji.io/dispatch.go:17
 3  0x0000000000a4200b in bitbucket.org/my/project/vendor/goji%2eio.(*dispatch).ServeHTTP
    at <autogenerated>:1
`

**Comment by freezlite** [comment]
Next stack after this
https://github.com/goji/goji/blob/master/dispatch.go#L17
Output from delve itself
` 
2  0x0000000000a3e67c in bitbucket.org/my/project/vendor/goji%2eio.dispatch.ServeHTTP
    at /home/freezlite/go/src/bitbucket.org/my/project/vendor/goji.io/dispatch.go:17
 3  0x0000000000a4200b in bitbucket.org/my/project/vendor/goji%2eio.(*dispatch).ServeHTTP
    at <autogenerated>:1
`

**Comment by ramya-rao-a** [comment]
@freezlite And how are you debugging this? Using tests? I dont see any code calling https://github.com/goji/goji/blob/master/dispatch.go#L11

**Comment by freezlite** [comment]
It's not mine code, but it crash debuger in vscode

**Pull request merged**
