### PR TITLE
Fix the goVersion to properly parse ver '1.10'

### PR DESCRIPTION
**Pull request by uudashr**
Previously go ver 1.10 parsed as "1.1"
Now fixed to as it should be "1.10"

This cause the "add import.." and "auto import unimported packages" broken

### CODE REVIEW

**Comment by uudashr** [comment]
This cause the "add import.." and "auto import unimported packages" broken

**Comment by uudashr** [comment]
Use default CC and CXX fix the golang "tip" issue
But somehow it failing on
1. Test Linter for Package
2. Fill struct – select non-struct line

**Comment by uudashr** [comment]
Use default CC and CXX fix the golang "tip" issue

But somehow it failing on
1. Test Linter for Package
2. Fill struct – select non-struct line

@ramya-rao-a need help.. maybe you know what the cause?

**Comment by uudashr** [comment]
Fix the lint test, the output has changed.. 
```
> gometalinter --disable-all --enable=golint --enable=errcheck .
linter_1.go:5:1:warning: exported function ExportedFunc should have comment or be unexported (golint)
linter_1.go:8:3:warning: error return value not checked (a declared but not used) (errcheck)
linter_2.go:5:1:warning: error return value not checked (missing return) (errcheck)
```

**Comment by uudashr** [comment]
The output of the linter different for go version 1.10 vs prev version
go 1.10
```
linter_1.go:8:3:warning: error return value not checked (a declared but not used) (errcheck)
```

while prev version
```
linter_1.go:8:3:warning: error return value not checked (a declared but not used) (errcheck, errcheck)
```

Not sure which one is correct. But fixed the test anyway

**Comment by uudashr** [comment]
@ramya-rao-a all good now... please check

**Comment by ramya-rao-a** [comment]
Thanks @uudashr!

Sorry couldn't help you sooner, I was out all day.

I'll look at releasing an update tomorrow

**Pull request merged**
