### PR TITLE
Support editor.formatOnSave

### PR DESCRIPTION
**Pull request by ramya-rao-a**
#540

### CODE REVIEW

**Comment by aphistic** [comment]
This is really inconvenient.  There are only certain languages I would want auto formatting for and I don't want to turn it on completely just to have my Go code auto-formatted.

**Comment by chrisolsen** [comment]
The default value of `editor.formaOnSave` is `false` which overrides `go.formatOnSave` making things seem broken after getting the most recent update.

**Comment by ramya-rao-a** [comment]
This change has been reverted due to popular demand in the latest update. Will wait for VS Code to come up with language specific formatOnSave setting

**Comment by aphistic** [comment]
Thank you!

**Comment by ramya-rao-a** [comment]
@aphistic No problem.
Thanks for reporting issues and pain points. I get to learn something new each day :)

**Pull request merged**
