### PR TITLE
add support for go/packages version of godef (same as gocode)

### PR DESCRIPTION
**Pull request by stamblerre**
This PR adds support for installing and switching between the regular version of godef and godef-gomod, which supports Go Modules (see https://github.com/Microsoft/vscode-go/pull/1932 for more details).

I'm not sure if this is the correct approach, but I basically copied the changes that were made for gocode. This change also requires @ianthehat to merge the "packages" branch of https://github.com/ianthehat/godef into master, because I don't believe that VSCode supports "go getting" certain branches (even though Modules does).

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
Closing in favor of 
https://github.com/Microsoft/vscode-go/commit/a20d42e93217426c611b9551b9b469279ea6dc75

**Comment by ramya-rao-a** [comment]
@stamblerre Can you remove the current binaries you have for `godef-gomod` and `gocode-gomod` try the latest [beta-version](
https://github.com/Microsoft/vscode-go/wiki/Use-the-beta-version-of-the-latest-Go-extension)?

It should give you appropriate prompts to install/update the required tools.

**Comment by stamblerre** [comment]
@ramya-rao-a The installation actually didn't work for me, I think because you deleted the "allTools[tool]" argument was deleted in this change (https://github.com/Microsoft/vscode-go/commit/094b704536e94a0f1f7a7bc0c13f62dcd3604e86#diff-3f57b095642b0ee445d6cdbc4f60d751).

**Comment by ramya-rao-a** [comment]
:) Yes, I found that out too. My mistake. The vsix is updated. Can you try again?

**Comment by stamblerre** [comment]
gocode seems to work fine, but I wasn't prompted to install godef. I had to click "Analysis tools missing" and then I got the godef installation, but it still isn't letting me jump to definitions.

**Comment by ramya-rao-a** [comment]
I get the prompt when I hit F12 on any symbol

screen shot 2018-09-26 at 4 15 14 pm

Can you remove the binary again, and debug the latest from master?

Also, your master branch seems to have a lot of merge commits :) I would suggest to nuke that branch and create a new "master" from this repo.

**Pull request closed without merging**
