### PR TITLE
new: support for showing coverage on single function test. closes #1637

### LINKED ISSUE #1637: [feature] add the coverage for single test run
Code coverage highlighting only works when we run the package tests.

Would it be possible to have the coverage when we run individual test function? This would be very helpful to see what a test function is actually testing, without having other tests interfering when we run all of them.

Thanks,

### PR DESCRIPTION
**Pull request by primalmotion**
I took a shot at implementing #1637.

### CODE REVIEW

**Comment by primalmotion** [comment]
hum the test failed, on go tip, and I don't think really understand how it would be related to my changes :/

**Comment by lggomez** [comment]
@primalmotion the ci log shows that the linter failed: https://travis-ci.org/Microsoft/vscode-go/jobs/368922868#L877

Run the TS linter on the files you changed and try again

You can install it here: https://marketplace.visualstudio.com/items?itemName=eg2.tslint

**Comment by primalmotion** [comment]
lint is fixed, but test are failing on go:tip

**Comment by primalmotion** [comment]
Sure I can add a new parameter.

**Comment by primalmotion** [comment]
@ramya-rao-a added requested changes

**Comment by ramya-rao-a** [comment]
Thanks!

**Comment by primalmotion** [comment]
Thanks!

**Pull request merged**
