### PR TITLE
Use  mod file to determine module mode when debugging

### PR DESCRIPTION
**Pull request by ramya-rao-a**
This PR attempts to fix the issue in #2828 where code under GOPATH gets debugged under the assumption that we are not in module mode if GO111MODULE is not `on`.

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
@SteelPhase I put something together that should help with #2828, but I haven't had the time to test it. Do you think you can take this for a spin? :)

**Comment by SteelPhase** [comment]
I'll try it out in the morning, and report back

**Comment by SteelPhase** [comment]
Tested it in outside of GOPATH and it works ok. When I test it inside GOPATH i get `Failed to continue: "TypeError: launchArgs.packagePathToGoModPathMap.get is not a function"`

**Comment by ramya-rao-a** [comment]
Thanks @SteelPhase, can you try again?

**Comment by SteelPhase** [comment]
This appears to be working as expected

**Pull request merged**
