### PR TITLE
readme: more info about the linter features

### PR DESCRIPTION
**Pull request by mattetti**
I didn't realize that a lot of the great go tools were already supported thanks to gometalinter. I was particularly interested in running `errcheck` on save (it verifies that all errors are being handled).  The linter change wasn't really documented and I didn't even realize that by switching linter I would get access to all these amazing tools.

This PR is a simple README update that explains what is a linter, how to change it and how to setup/customize gometalinter.

cc @egamma

### CODE REVIEW

**Comment by mattetti** [comment]
@joaomoreno @egamma is there anyone at Microsoft still maintaining this extension. I noticed Luke isn't there anymore and I'm afraid to see PRs piling up and this extension not getting too much love.

**Comment by egamma** [comment]
@mattetti as @lukehoban took on a new challenge he has obviously less cycles to support the extension. We are now ramping up a new team member for this extension, it is important to us, but there is a transition time.

**Comment by mattetti** [comment]
@egamma thanks for the update, very much appreciated. As an invested user, let me know if there is anything I can do to help.

**Comment by lukehoban** [comment]
I've been slow on keeping up with the issues and PRs, but still available to help keep things going with the extension.  I'm going to try and get through a bit of the PR backlog in particular - there's some really good improvements here.

**Comment by lukehoban** [comment]
Thanks for the documentation improvements for using `gometalinter`.

**Comment by mattetti** [comment]
@lukehoban thanks! I have been thinking about a few features I'll try to work on over the next weeks. I'll open issues for feedback. 

After looking through the code, I realize that contributing is pretty straightforward, thanks a lot for a great extension.

**Pull request merged**
