### PR TITLE
Use the newly added receiver output from godef to get the correct documentation

### PR DESCRIPTION
**Pull request by segevfiner**
Use the newly added receiver output from godef to get the correct documentation

See rogpeppe/godef#105

Part of #2107

⚠️ Depends on https://github.com/Microsoft/vscode-go/pull/2215 and the godef PR being merged

### CODE REVIEW

**Comment by segevfiner** [comment]
Receivers are really common, I think it's best to have the user update IMHO.

**Comment by segevfiner** [comment]
About https://github.com/Microsoft/vscode-go/blob/latest/src/goDeclaration.ts#L170... Does that even work?, It's a return inside the `child_process.execFile` callback, which is going to become the return value of the callback rather than the return value of the surrounding function.

**Comment by ramya-rao-a** [comment]
I do recall testing this but now that I look at the code, I am doubtful. It should most likely be

```
if (stderr && stderr.startsWith('flag provided but not defined: -tags')) {
	p = null;
	return definitionLocation_gogetdoc(input, token, false).then(resolve, reject);
}
```

**Comment by ramya-rao-a** [comment]
I take back my objection for keeping the prompt for updating the tool.

At this point, `godef` not only has the new `-r` flag but also has the module support. I was thinking of having some kind of update notification for the latter, but the current prompt will do the trick for both features.

**Comment by segevfiner** [comment]
@ramya-rao-a Oh noes.... The PR for godef wasn't merged yet! Like that it's just going to request people to update godef ad nauseum...

**Comment by ramya-rao-a** [comment]
@segevfiner I trusted you!!!!

Lol, kidding. I should have checked if the upstream PR was merged or not.
Let me reach out to the project maintainers there.
For now, I'll just push a commit to not use the `-r` flag

**Comment by segevfiner** [comment]
I did add a warning about this in the PR description, guess it didn't stand out enough enough. :man_shrugging:

**Pull request merged**
