### PR TITLE
Added configuration to use legacy Find All References

### PR DESCRIPTION
**Pull request by jonbonazza**
This is in response to #1491 .

So there are a couple things here that I am still not sure about, having never written a VSC plugin before and not being super fluent in TS/JS:

There is still one issue that I can't figure out though. Maybe someone else has an idea:

When sideloaded, while there doesn't seem to be a regression when ```go.legacyReference``` is _disabled_ (the default)--that is, it still works as usual without issue, however when ```go.legacyReference``` is _enabled_, it seems to find _some_ references, but most symbols that it should find are missing, and sometimes no symbols are found at all. This legacy code was taken directly from commit history, so Im not sure what I am missing here. Furthermore, I ran the ```go-find-references``` command externally and even it only finds a subset of the expected symbols. I'm not sure if go-find-references is just broken or if I am using it incorrectly.

### CODE REVIEW

**Comment by jonbonazza** [comment]
Also, I am not really sure why Travis is failing. Any insight here?

**Comment by ramya-rao-a** [comment]
> Also, I am not really sure why Travis is failing. Any insight here?

Travis is failing due to linting errors. Run `npm run lint` to see what errors these are.

> go-find-references is just broken or if I am using it incorrectly.

Based on https://github.com/Microsoft/vscode-go/issues/340#issuecomment-224313736 I'd guess that `go-find-references` should atleast give all the results that `guru` gives with some additional false positives, but your experiments seem to be concluding otherwise.

One thing to check is the value being passed to `root`. When you tested, were your expected references all inside the folder that was opened in VS Code?

**Comment by ramya-rao-a** [comment]
I wouldnt add the support for `go-find-references` back until we are more satisfied with its results.
If all it does is a fancy text search, then VS Code can do the same out of the box

**Comment by jonbonazza** [comment]
I agree. I was hoping someone here would be able to see sonething stupid i
was doing or missing. Mind giving it a try yourself and see if your results
are different?

**Comment by jadengore** [comment]
Any status updates on this? Would be cool to test out the performance of this. I find the Go Language Server from Sourcegraph to still be quite slow when looking up references.

**Comment by ramya-rao-a** [comment]
Closing as per https://github.com/Microsoft/vscode-go/issues/1491#issuecomment-468966736

**Pull request closed without merging**
