### PR TITLE
initial oracle support using codeLens #8

### PR DESCRIPTION
**Pull request by tecbot**
Make it possible to show CodeLens using the oracle command.
Currently, only the implements mode is implemented.

### CODE REVIEW

**Comment by lukehoban** [comment]
Great! Thanks for looking at this.  Really excited about this.

A few  initial thoughts from trying out the current code:

1. Could you add a new configuration setting in `package.json` and put this feature behind a feature flag?  That will make it easier to merge early without risking the default editing experience.
2. When I use this and then edit my source file I see it get out-of-date and then get stuck showing incorrect information.
3. It will be interesting to discuss what lenses make sense for Go, and which to display where.  For example, I can imagine that `implements` I can imagine it may make sense to show all the implementors of an interface on the interface itself, and the interfaces implemented by a struct on the struct, but may not make sense to put all of the interface method information at the method level.  But it will be interesting to see what info is available and then make some decisions on this.
4. Do you have a list in mind of the Oracle features you'd like to show in CodeLens?

**Comment by newhook** [comment]
Can resolve the state information in the same way I did with flymake? Write a temporary file with the current editor content and run oracle on that?

**Comment by newhook** [comment]
The right hands side list seems to be off by one. It should show the type names, not the line _after_ the type names?

oracle

**Comment by newhook** [comment]
I've asked for clarification from Alan Donovan on how we can get more complete information from oracle implements.

One side effect of this change is all sorts of additional empty lines in the editor before type defintions. Is there anything that can be done about that?

**Comment by lukehoban** [comment]
> One side effect of this change is all sorts of additional empty lines in the editor before type defintions. Is there anything that can be done about that?

I don't think we'll want to turn this feature on until there is useful information in the CodeLens display for every top level declaration.  At that point, there shouldn't be any empty lines, but there will be decorations on each declaration.

Here's what it looks like for C# currently in Code.  I think the "references" provider is one we'd ideally want to add early as it applies meaningfully to every declaration (and we have the find-all-reference feature that can be triggered when clicking it).  I am not sure though whether finding references is fast enough to use in this context.

codelens

**Comment by lukehoban** [comment]
@tecbot While I sort of agree about this being a failure of Code itself, I actually think that it makes sense to focus on providing information that will make sense to display on all declarations.  If we are going to show CodeLens at all, it makes sense for it to be consisentnly applied on all declarations and to show generally useful information.

I'm honestly still not sure what set of things from Oracle will make sense to display in this sort of UX vs. in a more on-demand UX like Pythia.

**Comment by newhook** [comment]
This is why implements is a bit brain dead.

https://github.com/golang/go/issues/13457

**Comment by newhook** [comment]
Apparently the Oracle bug is fixed.

**Comment by newhook** [comment]
So with the oracle bug fix implements now can take quite some time.

oracle -pos=$GOROOT/src/io/io.go:\#9401 implements  27.02s user 2.11s system 425% cpu 6.845 total

**Comment by lukehoban** [comment]
@newhook Yeah - that's unfortunate.  Sounds like that may be too slow to use in this particular UX.  We could still think about some other UX for exposing this command?  

I'm also still generally curious on what other things make sense to show in the CodeLens UX.

**Comment by newhook** [comment]
I haven't tried it in my large code base since the fix. I'll give it a try tomorrow.

I'd really like support for callers. Where do you think that makes sense? A right-click menu?

**Comment by lukehoban** [comment]
To be clear, I'd love to try it out and see what it feels like to put these things in CodeLens.  If they can work there, the UX is a really nice way to provide this info in context.  

If we decide they don't work there, we'd have to go with a command accessible through the palette and keybindings (and possibly context menu if that's possible yet?).

**Comment by ironcladlou** [comment]
This is probably worth revisiting with the new `guru` tool (see https://github.com/Microsoft/vscode-go/issues/284).

**Comment by mattetti** [comment]
I believe this feature was implemented using the contextual menu > Find all references, maybe we should close this PR (which is quite outdated).

**Comment by ironcladlou** [comment]
>I believe this feature was implemented using the contextual menu > Find all references, maybe we should close this PR (which is quite outdated).

Agree that this should be closed as inactive.

**Comment by ramya-rao-a** [comment]
Closing as this is outdated

**Pull request closed without merging**
