### PR TITLE
Do not show blank identifiers in file outline

### LINKED ISSUE #1889: Outline should exclude `_` "blank identifier"
We use `var _` in the top-level of some of our Go files for various reasons, most notably the ["interface checks pattern"](https://golang.org/doc/effective_go.html#blank_implements) documented in Effective Go.

These should be excluded from the Outline view since they don't represent a real variable that can be referenced and they clutter the output.

For example this code will produce 3 entries for `_` in the outline view:
```go
package foo

var (
	_ io.Closer = Foo(nil)
	_ io.Closer = Bar(nil)
	_ io.Closer = Baz(nil)
)
```

### PR DESCRIPTION
**Pull request by ragurney**
Resolves #1889

### CODE REVIEW

**Comment by ragurney** [comment]
Needs a test, having trouble getting the `test.go` file to work.

**Comment by ramya-rao-a** [comment]
The `gogetdoc` related failures are because you don't have `gogetdoc` installed. Someone is working on updating the tests to not fail in such cases.

You can comment them and the gometalinter one while running your tests. Your changes are unrelated to them so you can safely ignore them.

> When trying to add a line such as var _ string = "foo", I get two new failures as well,

That is mostly because there are other tests using the same file and now all the line numbers are changing. Try this
- In the `fixtures` table, create a new folder for `outline` and add a go file there as your test file. Update all the outline related tests to use this file

**Comment by ramya-rao-a** [comment]
@ragurney If you merge from master branch now, you will not get those failures

**Comment by ragurney** [comment]
@ramya-rao-a sounds good, thanks! I think this PR is ready for another review.

**Comment by ramya-rao-a** [comment]
Looks great, Thanks!

**Pull request merged**
