### PR TITLE
goMain.ts add commands to Go: Show All Commands

### LINKED ISSUE #1822: Add Go to implementation cmd to the Go: Show all Commands for better discoverability
Proposal. Please, implement a function that shows which interfaces from the current scope are satisfied by the selected function.

### PR DESCRIPTION
**Pull request by vimalk78**
commands added :
 * Go to definition
 * Go to implementation
 * Go to symbol in file
 * Go to symbol in workspace

fixes #1822

### CODE REVIEW

**Comment by vimalk78** [comment]
screen shot 2018-10-01 at 1 39 40 pm

The four commands are added to `Go : Show all commands...`

**Comment by vimalk78** [comment]
not sure why the CI is failing

screen shot 2018-10-01 at 5 24 09 pm

**Comment by vimalk78** [comment]
@ramya-rao-a  , does this look OK?

**Comment by vimalk78** [comment]
@ramya-rao-a , please check.

**Comment by ramya-rao-a** [comment]
Also, I see that this is your first contribution to vscode-go. Welcome & Thanks!

**Comment by vimalk78** [comment]
thanks for your help !!
how do i claim the hactoberfest t-shirt :)

**Comment by ramya-rao-a** [comment]
The details must be in https://open.microsoft.com/2018/09/18/hacktoberfest-2018-microsoft/
That's all I know :)

**Pull request merged**
