### PR TITLE
Issue 57

### PR DESCRIPTION
**Pull request by newhook**
Provisional PR for issue 57. Requires github.com/newhook/go-symbols.

### CODE REVIEW

**Comment by newhook** [comment]
I'm continuing to work on go-symbols with some help from Alan Donovan. I have an implementation that is more than twice as fast as the one in my current repo, but am still thinking :)

It would be interesting to have some input from the vscode authors on what symbols exactly can be shown. It isn't documented, and code seems to only show func and type.

**Comment by egamma** [comment]
Adding @jrieken he can provide more information.

**Comment by newhook** [comment]
Thanks for that! IMO, code should show the symbols presented to the API. In this way it is up to the extension authors to decide what types of symbols are shown.

**Comment by jrieken** [comment]
@bpasero will know

**Comment by bpasero** [comment]
@newhook isn't the list documented here:

```typescript
	export enum SymbolKind {
		File,
		Module,
		Namespace,
		Package,
		Class,
		Method,
		Property,
		Field,
		Constructor,
		Enum,
		Interface,
		Function,
		Variable,
		Constant,
		String,
		Number,
		Boolean,
		Array
	}
```

If something does not show up nicely in vscode after you use those types it is most likely a bug on our end how these things are converted.

**Comment by bpasero** [comment]
Actually we do some filtering on the handler side and the list we allow is: 'class', 'interface', 'enum', 'function', 'method'

@aeschli can also chime in if this list should be configurable maybe.

**Comment by newhook** [comment]
Pushed change to maxBuffer. Also pushed changes to go-symbols to improve the speed, and fix the null issue if there are no symbols.

**Comment by newhook** [comment]
This PR has been languishing for some time...

**Comment by egamma** [comment]
Ping @lukehoban.

**Comment by lukehoban** [comment]
Sorry for the long delay on merging this.  Just re-reviewed and pulled this in.

**Pull request merged**
