### PR TITLE
upgrade https-proxy-agent from 2.2.2 to 2.2.4

### PR DESCRIPTION
**Pull request by hyangah**
https://github.com/nodejs/security-wg/blob/master/vuln/npm/505.json

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
This is a good catch @hyangah 

The dependency on https-proxy-agent is added via the `vscode-test` package which in itself has released an update with the latest https-proxy-agent

The right approach here is to update `vscode-test` which in turn would update `https-proxy-agent`

I have pushed a commit for the same to your branch.

**Comment by ramya-rao-a** [comment]
Also, looks like this is your first PR contribution to this project, Thanks & Welcome!

**Comment by ramya-rao-a** [comment]
Can you sign the CLA as linked in https://github.com/microsoft/vscode-go/pull/2917#issuecomment-561325261 please?

**Comment by ramya-rao-a** [comment]
Sorry @hyangah 
I found another PR (#2900) doing the same where the contributor had already signed the CLA, so am going with that for the moment.

**Comment by hyangah** [comment]
Thanks!

**Pull request closed without merging**
