### PR TITLE
Improvements for "go to implementation"

### PR DESCRIPTION
**Pull request by hummerd**
1. Not fail if guruOutput.to or guruOutput.to_method is undefined
2. If we looked for method implementation, go to method implementations only

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
Thanks @hummerd!

**Comment by hummerd** [comment]
I am glad I can help!

**Comment by ramya-rao-a** [comment]
@hummerd I'll be releasing an update on the coming Tuesday or Wednesday and your changes will be part of it.

Do you mind helping me out with some testing before that? All you have to do is
- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` from the location where the above is installed
- Reload vs code and use it like you would any other day and let me know if there are any issues.

**Comment by hummerd** [comment]
Ok, I've installed Go-latest.vsix. If anything goes wrong I will report about it.

**Comment by ramya-rao-a** [comment]
Thanks!

**Pull request merged**
