### PR TITLE
Show test status until a file is changed

### PR DESCRIPTION
**Pull request by dmage**
Small addition for #810.

### CODE REVIEW

**Comment by dmage** [comment]
Ugly fix for CI: Microsoft/vscode-extension-vscode#52

**Comment by ramya-rao-a** [comment]
What does this have to do with Microsoft/vscode-extension-vscode#52?

**Comment by dmage** [comment]
I'm about https://travis-ci.org/Microsoft/vscode-go/builds/205602472
Tests for this PR are red without changes in vscode-extension-vscode.

**Comment by ramya-rao-a** [comment]
All the Mac related tests were previously failing to connect to github: https://travis-ci.org/Microsoft/vscode-go/builds/205432409, so I wrongly assumed the current failure is due to the same reason.

vscode-extension-vscode hasn't been updated in months. Why do you think that the current failure `'base must be a non-empty string, or null/undefined.'` is related to vscode-extension-code?

**Comment by dmage** [comment]
https://github.com/ddliu/gulp-remote-src/commit/02953a1429023bffa418b4174a73282faa4018d9
This is the reason why tests will fail on Mac since yesterday.
I was able to reproduce this error on my macbook and found that vscode-extension-vscode uses empty string as a base.

**Comment by ramya-rao-a** [comment]
Thanks @dmage, looks like your PR to vscode-extension-vscode was merged.

**Pull request merged**
