### PR TITLE
Relativize source files passed to delve if possible

### PR DESCRIPTION
**Pull request by arifogel**
- add 'sourceRoot' launch configuration property
- fixes failure to set breakpoint when binary is built with trim-paths, e.g. via bazel
- possibly related to #1307

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/vscode-go/2908)

### CODE REVIEW

**Comment by arifogel** [comment]
Hmm. Breakpoint is getting hit, and variable inspection works. But there are some usability issues I need to clean up. WIll do over next couple days.

**Comment by arifogel** [comment]
Seems to work now. Remote debugging is unaffected - so if it didn't work before, it still won't work now.

**Comment by tschundler** [comment]
I'm looking forward to this hopefully helping with my Bazel Go debugging.
Sounds like this may resolve #3011

**Comment by yalcinmelihyasin** [comment]
I have just briefly looked at the plugin code so I cannot say much but have you tested it with different OS? I remember there were some issues with path separators on different OS. See #3011 for detailed information.

**Comment by yalcinmelihyasin** [comment]
Also, I don't know if this would help with generated go code e.g. proto files. Although, even if it would not, it is a step towards right direction.

**Comment by ramya-rao-a** [comment]
Hello all,

My apologies for the late response.

We have made some improvements in the way the path separators are used and mapped, but also realize the need to respect relative paths. We want to explore a few other alternatives before resorting to adding more fields/properties to the debug configuration as being done in this PR.

Please take a look at https://github.com/golang/vscode-go/issues/45 where @quoctruong has shared the current state of things and potential improvements. There is a linked PR that you can check out as well. We would appreciate your input there.

As for this PR, we will have to close it as we are currently in the midst of a repo move, see [We are moving](https://github.com/microsoft/vscode-go#we-are-moving---) section in our readme for more details. At the moment, we are not accepting any PR unless it is related to the move or critical bug fixes. 

Thanks for your efforts here and we hope to see you engage in the discussion in https://github.com/golang/vscode-go/issues/45

**Pull request closed without merging**
