### PR TITLE
use last gopath element when installing tools

### PR DESCRIPTION
**Pull request by jrwren**
https://github.com/Microsoft/vscode-go/issues/1966

### CODE REVIEW

**Comment by AlexRouSg** [comment]
Why use last? The `go get` behavior is to use the first.

**Comment by jrwren** [comment]
> Why use last? The `go get` behavior is to use the first.

I thought so too, but that is not what I observed. Can you double check that you observe it installing to first?

**Comment by AlexRouSg** [comment]
Yes, that is how I observe it to work on Linux and Windows. This is even documented behavior. 

https://golang.org/cmd/go/#hdr-Download_and_install_packages_and_dependencies

> When checking out a new package, get creates the target directory GOPATH/src/<import-path>. If the GOPATH contains multiple entries, get uses the first one. For more details see: 'go help gopath'.

**Comment by jrwren** [comment]
That is pretty definite documentation. I wonder why I think I observed what I observed. I'll change this.

I also had a question re: calling `go install`? Why use -o rather than calling `go install` with `GOPATH` set?

**Comment by jrwren** [comment]
I realize now that the same code paths in vscode-go are made to install the tools even when there is no GOPATH, e.g. the GOPATH is infered per project or the go project uses go modules. I'm going to change the index to 0 and hopefully that is acceptable.

**Pull request merged**
