### PR TITLE
Add go.buildEnvVars

### PR DESCRIPTION
**Pull request by resec**
Add `go.buildEnvVars` to support adding `GO111MODULE=on` as env. variables to support go mod in `go build` in vscode.

### CODE REVIEW

**Comment by ramya-rao-a** [comment]
We have a setting `go.toolsEnvVars` which we use to set the env variables when running all the Go tools. Is there a reason why you would want to have GO111MODULE set only for the build process?

**Comment by resec** [comment]
Yes, I know there is already `go.toolsEnvVars`.

But some go tools are not supporting `go mod` yet, if simply add `GO111MODULE=on` to all tools, in my Mac, some of them breaks. The same goes to set a global env var in bashrc etc.

**Comment by ramya-rao-a** [comment]
Can you give examples of how the Go tools that break when you set `GO111MODULE=on` in `go.toolsEnvVars` or as global env var?

**Comment by resec** [comment]
Here is part of my settings.json that is related to vscode-go.

```
    "go.formatTool": "gofmt",
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.gotoSymbol.includeImports": true,
    "go.autocompleteUnimportedPackages": true,
    "go.gotoSymbol.includeGoroot": true,
    "go.useLanguageServer": true,
    "go.testEnvVars": {
        "GO111MODULE": "on",
    },
    "go.testFlags": [
        "-v",
        "--count=1"
    ],
    "go.buildEnvVars": {
        "GO111MODULE": "on",
    },
    "go.vetOnSave": "package",
```

Here is my project `go.mod`

```
module XXXX/go

require (
	github.com/aws/aws-sdk-go v1.19.40
	github.com/dgrijalva/jwt-go v3.2.0+incompatible // indirect
	github.com/emersion/go-imap v1.0.0-beta.5
	github.com/emersion/go-imap-idle v0.0.0-20190519112320-2704abd7050e
	github.com/emersion/go-message v0.10.3
	github.com/emersion/go-smtp v0.11.1
	github.com/go-redis/redis v6.15.2+incompatible
	github.com/go-sql-driver/mysql v1.4.1
	github.com/go-test/deep v1.0.1
	github.com/gogs/chardet v0.0.0-20150115103509-2404f7772561
	github.com/golang/protobuf v1.3.1
	github.com/golang/snappy v0.0.1
	github.com/google/uuid v1.1.1
	github.com/grpc-ecosystem/go-grpc-middleware v1.0.0
	github.com/jaytaylor/html2text v0.0.0-20190408195923-01ec452cbe43
	github.com/jinzhu/gorm v1.9.8
	github.com/kr/pretty v0.1.0 // indirect
	github.com/labstack/echo v3.3.10+incompatible
	github.com/labstack/gommon v0.2.8 // indirect
	github.com/mattn/go-colorable v0.1.2 // indirect
	github.com/mattn/go-runewidth v0.0.4 // indirect
	github.com/olekukonko/tablewriter v0.0.1 // indirect
	github.com/olivere/elastic/v7 v7.0.1
	github.com/onsi/ginkgo v1.8.0 // indirect
	github.com/onsi/gomega v1.5.0 // indirect
	github.com/pierrec/lz4 v2.0.5+incompatible
	github.com/pkg/errors v0.8.1
	github.com/saintfish/chardet v0.0.0-20120816061221-3af4cd4741ca // indirect
	github.com/segmentio/kafka-go v0.2.4
	github.com/sirupsen/logrus v1.4.2
	github.com/spf13/cast v1.3.0
	github.com/ssor/bom v0.0.0-20170718123548-6386211fdfcf // indirect
	github.com/stretchr/testify v1.2.2
	github.com/valyala/fasttemplate v1.0.1 // indirect
	golang.org/x/crypto v0.0.0-20190513172903-22d7a77e9e5f
	golang.org/x/text v0.3.2
	google.golang.org/genproto v0.0.0-20190522204451-c2c4e71fbf69
	google.golang.org/grpc v1.21.0
	gopkg.in/yaml.v2 v2.2.2
)
```

Besides, I installed all vscode go tools.

With above settings.json and go.mod, if I remove the `go.buildEnvVars` part from settings.json. 
1) The "following link on imports" is not working.
2) And `go build` keeps saying cannot find any third party package I imported.
3) And auto-completion is extremely slow. Like`fmt.` needs at least seconds (up to minutes) for any hint to showup.

**Comment by ramya-rao-a** [comment]
Apologies for the late response @resec 

Going over your settings, it looks like you are using the language server.
When using the language server, the extension doesn't run `go build` on its own.
The extension expects the language server to run the diagnostics and return build errors.

cc @stamblerre on the affects of setting GO111MODULE to `on` when using the language server

**Comment by stamblerre** [comment]
`gopls` should work fine with any configuration of `GO111MODULE`, as long as you open VS Code to the root of your module (the directory containing the `go.mod` file). For specific issues with `gopls`, please file a new issue on the Go issue tracker: https://github.com/golang/go/issues/new.

**Comment by ramya-rao-a** [comment]
Thanks @stamblerre 

@resec Am closing this PR. Please open an issue if you see problems with the GO111MODULE when using the language server

**Pull request closed without merging**
