### PR TITLE
fix stopOnEntry

### PR DESCRIPTION
**Pull request by jhendrixMSFT**
Send a dummy thread to vscode when stopped on entry as there are no
threads in the process yet.
Send the stop event with the same dummy thread ID.

### CODE REVIEW

**Comment by jhendrixMSFT** [comment]
Fixes https://github.com/Microsoft/vscode-go/issues/763

**Comment by ramya-rao-a** [comment]
cc @quoctruong

**Comment by jhendrixMSFT** [comment]
Good question, I tried it and it doesn't work.  While I'm sure it can be fixed, I want to ask if we think this scenario is valuable?  If not then I suggest removing `stopOnEntry` from the `attach` option.
I personally feel like this isn't really useful and in my experience I don't recall other debuggers doing this.  However I might be overlooking some use case.

**Comment by quoctruong** [comment]
Yes, I think by default, the program for remote attach scenario wouldn't start until a debugger is connected to it anyway. Therefore, this option may not be needed for that.

**Comment by jhendrixMSFT** [comment]
@ramya-rao-a are you ok with removing `stopOnEntry` from `attach`?

**Comment by ramya-rao-a** [comment]
@jhendrixMSFT Yes, I am fine with removing stopOnEntry for attach scenarios and ignore it for the launch request in debug mode as well

**Pull request merged**
