### PR TITLE
Use Go’s new logo

### LINKED ISSUE #2255: Change Extension logo to the new Go logo
Currently there will be this logo used for the extension store:
https://github.com/Microsoft/vscode-go/blob/master/images/goIcon.png

What about using the new Go logo from their styleguide?

Reference:
- https://blog.golang.org/go-brand
- https://golang.org/s/logos

Some idea:
image

### PR DESCRIPTION
**Pull request by dmundt**
Fixes #2255

The new logo follows the brand’s core philosophy of simplicity over complexity. Using a modern, italicized sans-serif typeface combined with three simple motion lines forms a mark that resembles two wheels in rapid motion, communicating speed and efficiency. The circular shape of the letters hints at the eyes of the Go gopher, creating a familiar shape and allowing the mark and the mascot to pair well together (https://blog.golang.org/go-brand).

"The gopher is not the logo. It should not be used instead of the logo." (see https://golang.org/s/brandbook, pp 21)

### CODE REVIEW

**Comment by dmundt** [comment]
@ramya-rao-a Thanks for considering this PR for merging.

**Comment by ramya-rao-a** [comment]
No problem at all, the latest update (0.11.1) to the extension has this change.
I just realized that the banner color needs to be updated as well

See https://marketplace.visualstudio.com/items?itemName=ms-vscode.Go

image

Do you mind sending a PR to fix the background color to something more pleasant :) ?
The change should be done in package.json under `galleryBanner`

**Comment by dmundt** [comment]
I'll be trying to change the banner color and send you a PR soon.

**Comment by dmundt** [comment]
@ramya-rao-a see PR #2631 for an updated gallery banner's background color hopefully more eye-friendly

**Comment by ramya-rao-a** [comment]
https://twitter.com/ramyanexus/status/1146550997801558016

**Pull request merged**
