### PR TITLE
Fixed line endings for scripts/terminateProcess.sh

### PR DESCRIPTION
**Pull request by fasa123**
Since the file has Windows line endings bash/sh cannot execute the file under Linux which is illogical since it is only ran under Linux (/Mac). Changed the endings from CRLF to LF now the debugger works again fine 

see https://github.com/Microsoft/vscode-go/issues/834 and https://github.com/Microsoft/vscode-go/issues/438

### CODE REVIEW

**Comment by roblourens** [comment]
Are you sure you didn't just check out CRLF line endings? They are LF on my machine

**Comment by fasa123** [comment]
Hi, 
Yes you are right the git source uses LF you can discard this pull request.

Though the extension that you install from the extension explorer of vscode appearently uses a version which uses Windows endings. The pull request is from my ~/.vscode/extensions and that one used CRLF which is also why so many people did have this problem.  Just update that one and everything will work.

**Comment by roblourens** [comment]
@fasa123 I see it now, yeah it was published with CRLF endings. But when I fix that locally, it actually still reproes for me...

**Comment by kisPocok** [comment]
I've also fixed the CRLF ending locally but the bug still there.

**Comment by roblourens** [comment]
Actually, it wasn't working when I just resaved the file with LF, but I deleted and recreated it with LF, and now it works. That's weird. Also, doing the opposite (running out of sources, changing LF to CRLF) broke it in the same way. So I think this is likely the problem.

**Comment by kisPocok** [comment]
The current master version works for me. No errors so far.

**Comment by roblourens** [comment]
@fasa123 Did you also have to `chmod +x terminateProcess.sh`?

**Comment by roblourens** [comment]
To make this work I have to chmod +x, and fix the line endings. When I publish an extension with a .sh from Mac, it comes out with the x flag automatically. Apparently that's not the case from Windows, so maybe we just have to always publish from mac/linux?

**Comment by ramya-rao-a** [comment]
Just published from a Mac

@kisPocok @fasal123 @YCF Can you get the latest version and confirm if things work for you?

**Comment by kisPocok** [comment]
Eureka, it works! 👍

**Comment by YCF** [comment]
@ramya-rao-a 
It works well!

**Comment by ramya-rao-a** [comment]
woohoo!

**Comment by fasa123** [comment]
Yes I did have to chmod as well.
And yes the extension works now.

**Comment by roblourens** [comment]
Great! Thanks for pointing out the line ending issue.

**Pull request closed without merging**
