### PR TITLE
Add support for coverage markup

### PR DESCRIPTION
**Pull request by tampajohn**
Adding coverage highlighting to vscode-go.  Adds setting "go.coverageOnSave" and command for performing coverage for current package.  Addresses some of the desires of #80.

### CODE REVIEW

**Comment by tampajohn** [comment]
@tecbot Hmmmm, I'm not super sure where the best place to tie into this is... @lukehoban I know I could do something using registerOnTypeFormattingEditProvider, but that seems kinda invasive... do you know a good place to handle resetting coverage when a document is dirty?

**Comment by lukehoban** [comment]
Depends a bit on what experience you want exactly.  

You could try [`workspace.onDidChangeTextDocument`](https://github.com/Microsoft/vscode-extension-vscode/blob/master/vscode.d.ts#L3012) which sends a notification when any open text document changes.

But do you think it makes sense to instead try to keep the coverage information around even after you make edits?

**Comment by tampajohn** [comment]
@tecbot Removing coverage for the file that's been edited, thanks for the onDidChangeTextDocument pointer @lukehoban

**Comment by rs** [comment]
What is the status of this PR? What’s missing for its merging?

**Comment by lukehoban** [comment]
Finally got a chance to re-review this, and looks good.

I've merged this in now along with a few minor changes.

Thanks @tampajohn, and apologies for the 4 month delay :smile:.

**Pull request merged**
