### PR TITLE
fix #2134

### LINKED ISSUE #2134: TypeError: Cannot read property 'length' of undefined
There is an exception happening:
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3309 TypeError: Cannot read property 'length' of undefined
	at runGoCode.then.suggestions (/Users/sardorbek/.vscode/extensions/ms-vscode.go-0.7.0/out/src/goSuggest.js:131:37)
	at <anonymous>
e.$onExtensionRuntimeError @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:3309
```
screenshot 2018-11-20 at 09 50 38

### PR DESCRIPTION
**Pull request by oneslash**
I am trying to fix #2134

### CODE REVIEW

**Comment by oneslash** [comment]
I will fix it today

**Comment by oneslash** [comment]
@ramya-rao-a, could you check now?

**Comment by oneslash** [comment]
@ramya-rao-a, would be great if you can look into it soon :)

**Comment by ramya-rao-a** [comment]
Congratulations on getting your first PR in this repository merged!
Feel free to pick up any other issue with the `help-wanted` label. I appreciate all the help I can get :)

**Pull request merged**
