### PR TITLE
Support for flymake.

### PR DESCRIPTION
**Pull request by newhook**
This is a preliminary PR. This requires https://github.com/newhook/goflymake from my repo, as the original does not support multiple flymake files.

Please check for basic structure and whether you think this is acceptable in general before I fix the  below.

Things I know which require work:
- auto build and flymake are incompatible (but not lint/vet), but I didn't implement that (yet).
- didn't add a flymake config option.
- The path to goflymake is hard coded (the repo doesn't yet work correctly with multi-path GOPATH).
- Only tested on OSX.

### CODE REVIEW

**Comment by newhook** [comment]
I remember an issue on this, but the linting doesn't show errors from other sources files which I find less than desirable. This is easily fixed:

Change:
cp.execFile(golint, [filename], {cwd: cwd}, (err, stdout, stderr) => {

to:

cp.execFile(golint, [], {cwd: cwd}, (err, stdout, stderr) => {

**Comment by lukehoban** [comment]
Thanks!

Generally this looks like a good start.  I'm open to moving the error checking over to this approach if we can get this as complete as the current solution.

Few things:

I'm seeing the `flymake_*` files being emitted next to the real source files.

When I make edits in `_test.go` files, I stop seeing any errors either in the `_test.go` file or in any of the other files (even ones that were displaying errors previously).

When I tried this on the `github.com/derekparker/delve` codebase (modifying the `proc/prog.go` file), I don't see any errors being reported but see this on stdout of the `goflymake` command:

```
      __cgo_d5684f8859a6_Cfunc_raise_exception in proc_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_raise_exception)
  "_read_memory", referenced from:
      __cgo_d5684f8859a6_Cfunc_read_memory in threads_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_read_memory)
  "_resume_thread", referenced from:
      __cgo_d5684f8859a6_Cfunc_resume_thread in threads_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_resume_thread)
  "_set_pc", referenced from:
      __cgo_d5684f8859a6_Cfunc_set_pc in registers_darwin_amd64.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_set_pc)
  "_set_registers", referenced from:
      __cgo_d5684f8859a6_Cfunc_set_registers in registers_darwin_amd64.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_set_registers)
  "_single_step", referenced from:
      __cgo_d5684f8859a6_Cfunc_single_step in threads_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_single_step)
  "_thread_blocked", referenced from:
      __cgo_d5684f8859a6_Cfunc_thread_blocked in threads_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_thread_blocked)
  "_thread_count", referenced from:
      __cgo_d5684f8859a6_Cfunc_thread_count in proc_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_thread_count)
  "_write_memory", referenced from:
      __cgo_d5684f8859a6_Cfunc_write_memory in threads_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_write_memory)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Are you aware of any other limitations or differences in behaviour in terms of when real errors will/wont be displayed after this change?

**Comment by newhook** [comment]
Cool, thanks for looking at that!

- For the flymake_ files I'm not sure what can reasonably be done here. New files have to be created in the same directory as the package otherwise go doesn't like that and we cannot overwrite the existing files. The only option I can see here is if the editor itself can supress showing these files?

- I cannot duplicate the issue that you pointed out with _test.go files. I only tested this with go 1.4, however.

- I duplicated the issue with delve and cgo. I haven't looked into this in great detail yet, however, this shows the same issue.

```
➜  proc git:(master) ✗ go build .
```

vs:

```
➜  proc git:(master) ✗ go build arch.go breakpoints.go doc.go eval.go go_version.go proc.go proc_darwin.go ptrace_darwin.go registers.go registers_darwin_amd64.go threads.go threads_darwin.go variables.go
# command-line-arguments
Undefined symbols for architecture x86_64:
  "_acquire_mach_task", referenced from:
      __cgo_d5684f8859a6_Cfunc_acquire_mach_task in proc_darwin.cgo2.o
     (maybe you meant: __cgo_d5684f8859a6_Cfunc_acquire_mach_task)
```

**Comment by lukehoban** [comment]
Per https://github.com/Microsoft/vscode-go/issues/31#issuecomment-159697233 I'm going to close out the PR for now.  Feel free to reopen if you want to keep working on this.

**Pull request closed without merging**
