### PR TITLE
if buildOnSave is on: build using -i

### PR DESCRIPTION
**Pull request by mattetti**
This PR addresses the compilation performance optimization discussed in #673.

Installing the built packages improves following compilations since packages are only rebuilt if they changed.
If the current package is a main package, the installation is skipped to avoid installing executable binaries.

I had to tweak a util method that was scanning text files to find the package and the imports. Unfortunately this util wasn't tracking the name of the package. I needed the package name to check if the `-i` flag should be used or not.

### CODE REVIEW

**Comment by mattetti** [comment]
@ramya-rao-a would you mind helping me understand what's wrong with the test suite? I seem to have broken something on macOS. The failures don't make too much sense to me :(

**Comment by ramya-rao-a** [comment]
@mattetti The 2 tests are failing because they are not getting back expected errors from `go build`.
You are reading the file using `fs.readFile` and calling the `runTool` in the callback. By the time the callback is called, the test has already completed, and so does not get the results of `go build`.

Here is what you can try:
```
let buildPromise = new Promise<ICheckResult[]>((resolve, reject) => {
    fs.readFile(filename. 'utf8', (err, data) => {
        .....
        runTool(....).then(result => return resolve(result), err => return reject(err));
    }
});
runningToolsPromises.push(buildPromise);
```

**Comment by mattetti** [comment]
perfect thank you! I'll give it a try

**Comment by mattetti** [comment]
@ramya-rao-a PR updated, tests are now passing, thanks for your help!

Note, this PR is pending the resolution of the discussion happening there: https://github.com/Microsoft/vscode-go/issues/673

**Pull request merged**
